name: Codecov

on: [push]

jobs:
  codecov:
    name: "Codecov pipeline"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Setting MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: "5.7.17"
        mysql root password: "test"
        mysql database: 'test'
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Generate passport keys
      run: php artisan passport:keys
    - name: Generate swagger docs
      run: php artisan l5-swagger:generate
    - name: Execute tests for codecov
      run: vendor/bin/phpunit --coverage-clover=coverage.xml
    - name: Upload coverage report
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
