name: Quasar
on: [push]
jobs:
  build:
    name: Quasar
    runs-on: ubuntu-latest
    steps:
      - name: Install Quasar
        run: npm install -g @quasar/cli
      - name: Install Quasar
        run: cd cordova && npm install
      - name: Run Quasar build
        run: cd cordova && npm run build
